//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadwagE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_V_EW1_WAZENIA
    {
        public long id { get; set; }
        public Nullable<long> ID_TRANS { get; set; }
        public System.DateTime DATE { get; set; }
        public string ARTICLE_NAME { get; set; }
        public string BALANCE_NAME { get; set; }
        public Nullable<float> MASS_ELEMENTARY { get; set; }
        public string ARTICLE_NAME_LONG { get; set; }
        public string UNIT { get; set; }
        public Nullable<int> COUNT { get; set; }
        public string OPERATOR { get; set; }
        public string COOPERATOR_NAME_LONG { get; set; }
        public string COOPERATOR { get; set; }
        public string SOURCE { get; set; }
        public string DESTINATION { get; set; }
        public string CODE_SERIES { get; set; }
        public Nullable<float> PRICE { get; set; }
        public Nullable<short> DISCOUNT { get; set; }
        public string EXTRA_FIELD_CBS { get; set; }
        public Nullable<int> PLATFORM_NUMBER { get; set; }
        public string EXTRA_FIELD_uboj_klasyfikacja { get; set; }
        public string EXTRA_FIELD_uboj_otluszczenie { get; set; }
        public string EXTRA_FIELD_uboj_tatuaz { get; set; }
        public Nullable<System.DateTime> DATE_OF_GETTING { get; set; }
        public Nullable<float> TEMPERATURE { get; set; }
        public Nullable<System.DateTime> DATE_OF_USABILITY { get; set; }
        public Nullable<float> MASS { get; set; }
        public Nullable<float> MASSBRUTTO { get; set; }
        public Nullable<float> MASSBRUTTO_ARTYS { get; set; }
        public Nullable<float> MASS_KG { get; set; }
        public Nullable<int> ID_ORDER { get; set; }
        public float MASS_SI { get; set; }
        public string CODE_SERIE_TRANS { get; set; }
        public Nullable<int> MASS_FROM_HAND { get; set; }
        public Nullable<int> VALVE_COUNT { get; set; }
        public Nullable<double> MASS_TO_DOSE { get; set; }
        public Nullable<long> WEIGHT_NUMBER_FOR_GOODS { get; set; }
        public Nullable<long> WEIGHT_NUMBER_FOR_ORDER { get; set; }
        public Nullable<long> WEIGHT_NUMBER_IN_DAY { get; set; }
        public Nullable<int> ID_PALLETE { get; set; }
        public string LINE { get; set; }
        public Nullable<long> zlecenie_rec_szczegoly_id { get; set; }
        public Nullable<long> EXTRA_FIELD_uboj_skup_id_kontrah { get; set; }
        public Nullable<float> TARE { get; set; }
        public Nullable<int> NUMBER_IN_TRANSACTION { get; set; }
        public Nullable<int> id_brygada { get; set; }
        public Nullable<double> MAX_ARTICLE { get; set; }
        public Nullable<double> MIN_ARTICLE { get; set; }
        public string RECEPTURE_SERIES { get; set; }
        public string RECEPTURE_CODE { get; set; }
        public string EXTRA_FIELD_nr_kolczyk { get; set; }
        public Nullable<float> EXTRA_FIELD_cena_dnia2 { get; set; }
        public Nullable<short> BOX { get; set; }
        public Nullable<float> PACKAGE_MASS { get; set; }
        public Nullable<int> PACKAGE_COUNT { get; set; }
        public Nullable<int> id_prac { get; set; }
        public string SCODE_ARTICLE { get; set; }
        public string SCODE_CONTRACTOR { get; set; }
        public string PACKAGE_SORT { get; set; }
        public string EXTRA_FIELD_uboj_klasa { get; set; }
        public Nullable<float> MASS_SI_ALWAYS_G { get; set; }
        public string ORDER_SYMBOL { get; set; }
        public string TRANS_SYMBOL { get; set; }
        public Nullable<int> PartiaOk { get; set; }
        public string Podzl_ew_symbol { get; set; }
        public string Zlecenie_ew_symbol { get; set; }
        public Nullable<long> scale_id { get; set; }
        public string NAZWA_TOWAR_WYNIK { get; set; }
        public string kod_serii2 { get; set; }
        public Nullable<bool> archiwalne { get; set; }
        public Nullable<bool> ZlecResztki { get; set; }
        public Nullable<long> zlecenie_rec_id { get; set; }
        public string ZlecRecNr { get; set; }
        public string ZlecRecNazwa { get; set; }
        public Nullable<float> MasaZmierzonaNettoKg { get; set; }
        public Nullable<float> ubytekKG { get; set; }
        public string RecepturaNazwa { get; set; }
        public Nullable<float> wartosc_netto { get; set; }
        public Nullable<float> wartosc_brutto { get; set; }
        public Nullable<float> vat { get; set; }
        public Nullable<bool> towar_ok { get; set; }
        public Nullable<byte> status_wazenia { get; set; }
        public Nullable<byte> Status_Kalibracji { get; set; }
        public Nullable<long> Oper_id { get; set; }
        public string TypWagi { get; set; }
        public Nullable<float> MasaBruttoSI { get; set; }
        public Nullable<float> TareSI { get; set; }
        public string OperatorKontrolny { get; set; }
        public string Platforma_Nazwa { get; set; }
        public Nullable<int> Platforma_Numer { get; set; }
        public string TowarWynik { get; set; }
        public string uboj_miesnosc { get; set; }
        public string uboj_grubosc_miesnia { get; set; }
        public string uboj_nr_ubojowy { get; set; }
        public string uboj_klasa { get; set; }
        public Nullable<bool> PrzychodRozchod { get; set; }
        public Nullable<int> licznik_statystyka { get; set; }
        public Nullable<int> licznik_wazen { get; set; }
        public string SCODE_OPERATOR { get; set; }
        public string zm_uniw1 { get; set; }
        public string zm_uniw2 { get; set; }
        public string zm_uniw3 { get; set; }
        public string ZmDod1 { get; set; }
        public string ZmDod2 { get; set; }
        public string ZmDod3 { get; set; }
        public string ZmDod4 { get; set; }
        public string ZmDod5 { get; set; }
        public string masa_w_jednostce_str { get; set; }
        public Nullable<double> ktpw_t2_min { get; set; }
        public Nullable<double> ktpw_t2_max { get; set; }
        public string KTP_dokument_nr { get; set; }
        public Nullable<double> min { get; set; }
        public Nullable<double> max { get; set; }
        public Nullable<double> min2 { get; set; }
        public Nullable<double> max2 { get; set; }
        public string jedn_dod { get; set; }
        public Nullable<float> jedn_dod_ilosc { get; set; }
        public string PACKAGE_CODE { get; set; }
        public Nullable<decimal> MASS_IN_UNIT_ON_SCALE { get; set; }
        public string UNIT_ON_SCALE { get; set; }
        public string KTP_WEIGHTING_STATUS { get; set; }
        public string ARTICLE_CODE { get; set; }
        public Nullable<float> ARTICLE_QN { get; set; }
        public Nullable<double> ARTICLE_TARE { get; set; }
        public Nullable<double> ARTICLE_DENSITY { get; set; }
        public string Status_string { get; set; }
        public string OPERATOR2 { get; set; }
        public Nullable<double> BRUTTO { get; set; }
    }
}
