//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadwagE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ew1_kontrahenci
    {
        public long id { get; set; }
        public string nazwa { get; set; }
        public string nazwa_dl { get; set; }
        public string sKod { get; set; }
        public string opis { get; set; }
        public Nullable<bool> dostawca { get; set; }
        public Nullable<bool> klijent { get; set; }
        public string NIP { get; set; }
        public Nullable<float> rabat { get; set; }
        public Nullable<bool> rabat_kwotowo { get; set; }
        public string kod_etykiety { get; set; }
        public string impSymfonia { get; set; }
        public string impSubiekt { get; set; }
        public string zlecenie { get; set; }
        public Nullable<int> zlecenie_licznik { get; set; }
        public string impSub { get; set; }
        public Nullable<bool> archiwalny { get; set; }
        public string guid { get; set; }
        public Nullable<int> grupa { get; set; }
        public string kod_exp { get; set; }
        public string adres { get; set; }
        public string kod { get; set; }
        public string miejscowosc { get; set; }
        public Nullable<bool> spedytor { get; set; }
        public Nullable<System.DateTime> data_aktualizacji { get; set; }
        public Nullable<bool> IGNORE_TRIGGER { get; set; }
    }
}
